[package]
name = "auto-jni"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = { version = "0.21.1", features = ["invocation"] }
thiserror = "1.0"
once_cell = "1.18"
lazy_static = "1.5.0"
regex = "1.11.1"